# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: 'json' }
    view:
        view_response_listener: 'force'
        formats:
            json: true
            xml: true
    routing_loader: false
    # body_listener:
    #     enabled: true
    #     default_format: json
    #     formats:
    #         json:
    #             mime_types: ['application/json']
    #             decoders:
    #                 - app.serializer.book_decoder
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
