nelmio_api_doc:
    documentation:
        # servers:
        #   - url: /books
        #     description: API over HTTP
        info:
            title: My Book App
            description: This is an books app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

